import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark,shadesOfPurple } from "@clerk/themes";
import Navigation from "../components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
    appearance={{
      baseTheme: dark,
    }}>

    <html lang="en">
      <body className={`${inter.className} dark min-h-screen min-w-screen`}>
      <Navigation />
        {children}
        </body>
    </html>
    </ClerkProvider>
  );
}
